version: "3"

services:
  postgres:
    image: bitnami/postgresql:15
    container_name: quizdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=quizdb
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
